name: estimate
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
  # A powerful Http client for Dart, which supports Interceptors, Global configuration, FormData, 
  # Request Cancellation, File downloading, Timeout etc.
  dio: ^4.0.0
  
  # A dart package that helps implement the BLoC pattern.
  bloc: ^7.0.0

  #Draw SVG (and some Android VectorDrawable (XML)) files on a Flutter Widget.
  flutter_svg: ^0.22.0

  #Flutter widget that automatically resizes text to fit perfectly within its bounds.
  auto_size_text: ^3.0.0-nullsafety.0

  #A straightforward flutter form field validator that provides common validation options.
  form_field_validator: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #Simple, fast generation of RFC4122 UUIDs.
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/inAppLogo.svg
    - assets/images/intorTopLeftClip.svg
    - assets/images/introScreenBottomRightClip.svg
    - assets/images/loginActionScreenCenterLeftClip.svg
    - assets/images/loginActionScreenTopLeftClip.svg
    - assets/images/loginActionScreenTopRightClip.svg
    - assets/images/roundedAppBarClip.svg
    - assets/images/googlePlusIcon.svg
    - assets/images/linkedinIcon.svg
    - assets/icons/dropDownIcon.svg
    - assets/icons/emailPrefix.svg
    - assets/icons/passwordPrefix.svg
    - assets/icons/passwordSuffix.svg
    - assets/icons/adressPrefix.svg
    - assets/icons/behancePrefix.svg
    - assets/icons/buildingPrefix.svg
    - assets/icons/dribblePrefix.svg
    - assets/icons/linkedinPrefix.svg
    - assets/icons/locationPrefix.svg
    - assets/icons/userPrefix.svg
    - assets/icons/zipPrefix.svg
    - assets/icons/doneIcon.svg    
    - assets/icons/backIcon.svg
    - assets/icons/companyNameIcon.svg
    - assets/icons/positionIcon.svg
    - assets/images/inAppLogo.png
    - assets/images/splash.png
    - assets/images/logo.gif
    - assets/images/linearBackground.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
